# Statistics: Central Tendency

## Goals for Today {-} 

* Today we're going to be talking all about central tendency and dispersion! 
  * Note: we're going to take our time over these next two weeks as I know that not everyone will feel as comfortable as we enter into the "math" portion of the course. I'll provide as many links to supplemental materials and videos as possible to the "optional" reading area - so make sure to check those out! 

## Readings for Today {-} 

### Required {-}

* OpenIntro Statistics, **2.0,2.1,2.2** (Pages 39 - 71)
  * Note: you don't have to do the exercises! 
* Navarro, DJ., [Learning statistics with R: A tutorial for psychology students and other beginners - 5.1,5.2,5.3](https://bookdown.org/ekothe/navarro26/descriptives.html)
  * Note: you don't need the data or to code along -this may just be helpful supplemental reading to the textbook if you'd like to see these commands "in R". 

### Optional {-}

* If you're a little uncomfortable with math (and that's okay!), some of these YouTube videos could help as refreshers: 
  * [Khan Academy - Central Tendency](https://www.youtube.com/watch?v=k3aKKasOmIw) 
  * [Khan Academy - Measures of Dispersion](https://www.youtube.com/watch?v=E4HAYd0QnRc) 
  * [What is Kurtosis? (+ the "peakedness" controversy!)](https://www.youtube.com/watch?v=TM033GCU-SY)

## Important Links and Files {-}

* The file we worked on in class is available [here]()